# Generated by Django 5.2.4 on 2025-07-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="temp_otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
